.PHONY:  clean-build clean

help:
	@echo 'Usage: make [command]'
	@echo 'Commands:'
	@echo '  build        Build a distribution package with setuptools.'
	@echo '  install      Build and install a local dist package with pip.'
	@echo '  clean        Remove all Python, test and build artifacts.'
	@echo '  lint         Check code style.'

build:
	python setup.py egg_info sdist bdist_wheel
	ls -l dist

install: build
	pip install dist/*.tar.gz

clean: clean-build

clean-build:
	rm -fr build/
	rm -fr dist/
	rm -fr .eggs/
	rm -fr .env/
	find . -name '*.egg-info' -exec rm -fr {} +
	find . -name '*.egg' -exec rm -f {} +

clean-inference-file:
	rm `ls ./ | grep -E '^[1-9]'`

lint: flake8 pylint

flake8:
	. .env/bin/activate && flake8 --show-source --count

pylint:
	. .env/bin/activate && pylint detector --disable=missing-docstring,too-few-public-methods,too-many-ancestors,no-member